name: manolo
favicon: null
layout_spectrum: 0.39976111985743046
typography_spectrum: 0.5442369480151683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.67115872586146
  lightness: 0.12553109182044864
  saturation: 0.28859709738753736
  rhythmicContrast: 0.30282327672466636
purpose: []
